application:
  host: "localhost"

database:
  host: "localhost"
  username: "postgres"
  password: "password"

redis:
  host: "localhost"

email:
  api_uri: "http://localhost:5000/"
  sender: "test@gmail.com"
  key: "fake-key-alaag-aaga"
